.TH ITUSB1-UDOFF 1
.SH NAME
itusb1-udoff \- disable USB data on ITUSB1 USB Test Switch
.SH SYNOPSIS
.B itusb1-udoff
.RI [ SERIALNUMBER ]
.SH DESCRIPTION
.B itusb1-udoff
disables USB data on the USB test switch, essentially by disconnecting both data
lines (D+ and D-). Conversely, you can invoke
.B itusb1-udon
to connect the data lines. You can also verify the corresponding status by
calling
.BR itusb1-status .

Specifying a serial number is optional.
.SH "EXIT STATUS"
Exits with a status of zero in case of success. Returns one should an error
occur.
.SH AUTHOR
Samuel Lourenço (samuel.fmlourenco@gmail.com).
.SH "SEE ALSO"
itusb1-attach(1), itusb1-detach(1), itusb1-info(1), itusb1-list(1),
itusb1-lockotp(1), itusb1-reset(1), itusb1-status(1), itusb1-udon(1),
itusb1-upoff(1), itusb1-upon(1)
