.TH ITUSB1-UPOFF 1
.SH NAME
itusb1-upoff \- disable USB power, on ITUSB1 USB Test Switch
.SH SYNOPSIS
.B itusb1-upoff
.RI [ SERIALNUMBER ]
.SH DESCRIPTION
.B itusb1-upoff
disables USB power, on the USB test switch, by switching VBUS off between host
and device. Conversely, you can invoke
.B itusb1-upon
to switch VBUS on. You can also verify the corresponding status by
calling
.BR itusb1-status .

Specifying a serial number is optional.
.SH "EXIT STATUS"
Exits with a status of zero in case of success. Returns one should an error
occur.
.SH AUTHOR
Samuel Lourenço (samuel.fmlourenco@gmail.com).
.SH "SEE ALSO"
itusb1-attach(1), itusb1-detach(1), itusb1-info(1), itusb1-list(1),
itusb1-lockotp(1), itusb1-reset(1), itusb1-status(1), itusb1-udoff(1),
itusb1-udon(1), itusb1-upon(1)
