.TH ITUSB1-LIST 1
.SH NAME
itusb1-list \- list connected ITUSB1 USB Test Switch devices
.SH SYNOPSIS
.B itusb1-list
.SH DESCRIPTION
.B itusb1-list
lists all USB test switch devices that are currently connected. Note that the
first device on the list is always the one addressed by default. Hence, when
applicable, a command invoked without any serial number specified will always
take effect on that device.
.SH "EXIT STATUS"
Exits with a status of zero in case of success. Returns one should an error
occur.
.SH AUTHOR
Samuel Lourenço (samuel.fmlourenco@gmail.com).
.SH "SEE ALSO"
itusb1-attach(1), itusb1-detach(1), itusb1-info(1), itusb1-lockotp(1),
itusb1-reset(1), itusb1-status(1), itusb1-udoff(1), itusb1-udon(1),
itusb1-upoff(1), itusb1-upon(1)
